### ISSUE TITLE
Can't load the Lovelace UI

### ISSUE THREAD

**Issue by Kvasenok** [estevez-dev/ha_client_pub#35]
When trying to launch the app with Lovelace UI enabled the app simply won't load the UI.

Log:
```
1104 17:29:36 [Debug] :  AppLifecycleState.inactive
1104 17:29:36 [Debug] :  AppLifecycleState.resumed
1104 17:29:57 [Debug] :  Settings change event: reconnect=true
1104 17:29:57 [Debug] :  Use lovelace is true
1104 17:29:57 [Debug] :  Socket connecting...
1104 17:29:57 [Debug] :  [Sending] ==> auth request
1104 17:29:57 [Debug] :  [Sending] ==> {"id": 1, "type": "subscribe_events", "event_type": "state_changed"}
1104 17:29:57 [Debug] :  [Sending] ==> {"id": 2, "type": "get_states"}
1104 17:29:57 [Debug] :  [Sending] ==> {"id": 3, "type": "lovelace/config"}
1104 17:29:57 [Debug] :  [Sending] ==> {"id": 4, "type": "get_config"}
1104 17:29:57 [Debug] :  [Sending] ==> {"id": 5, "type": "get_services"}
1104 17:29:57 [Debug] :  [Sending] ==> {"id": 6, "type": "auth/current_user"}
1104 17:29:57 [Debug] :  Parsing 133 Home Assistant entities
1104 17:29:58 [Debug] :  Parsing lovelace config
1104 17:29:58 [Debug] :  --Title: Квартира
1104 17:29:58 [Debug] :  --Views count: 7
1104 17:29:58 [Debug] :  ----view id: 0
1104 17:29:58 [Error] :  NoSuchMethodError: Class '_TypeError' has no instance method '[]'.
Receiver: Instance of '_TypeError'
Tried calling: []("errorMessage")
1104 17:29:58 [Error] :  #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50)
#1      HomeAssistant._completeConnecting (file:///D:/src/hass_client/lib/home_assistant.class.dart:198)
#2      HomeAssistant._completeFetching (file:///D:/src/hass_client/lib/home_assistant.class.dart:177)
#3      HomeAssistant._getData (file:///D:/src/hass_client/lib/home_assistant.class.dart:171)
<asynchronous suspension>
#4      HomeAssistant.fetch.<anonymous closure> (file:///D:/src/hass_client/lib/home_assistant.class.dart:76)
#5      _rootRunUnary (dart:async/zone.dart:1132)
#6      _CustomZone.runUnary (dart:async/zone.dart:1029)
#7      _FutureListener.handleValue (dart:async/future_impl.dart:129)
#8      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642)
#9      Future._propagateToListeners (dart:async/future_impl.dart:671)
#10     Future._propagateToListeners (dart:async/future_impl.dart:569)
#11     Future._completeWithValue (dart:async/future_impl.dart:486)
#12     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:516)
#13     _rootRun (dart:async/zone.dart:1124)
#14     _CustomZone.run (dart:async/zone.dart:1021)
#15     _CustomZone.runGuarded (dart:async/zone.dart:923)
#16     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963)
#17     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#18     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)

1104 17:30:07 [Debug] :  AppLifecycleState.inactive
1104 17:30:07 [Debug] :  AppLifecycleState.paused
1104 17:30:17 [Debug] :  [Received] => event.state_changed: sun.sun
1104 17:30:30 [Debug] :  AppLifecycleState.inactive
1104 17:30:30 [Debug] :  AppLifecycleState.resumed
1104 17:30:30 [Debug] :  Use lovelace is true
1104 17:30:30 [Warning] :  Previous fetch is not complited
1104 17:30:48 [Debug] :  [Received] => event.state_changed: sensor.time
1104 17:31:17 [Debug] :  [Received] => event.state_changed: sun.sun
1104 17:31:27 [Debug] :  AppLifecycleState.inactive
1104 17:31:27 [Debug] :  AppLifecycleState.paused
1104 17:31:28 [Debug] :  AppLifecycleState.inactive
1104 17:31:28 [Debug] :  AppLifecycleState.resumed
1104 17:31:28 [Debug] :  Use lovelace is true
1104 17:31:28 [Warning] :  Previous fetch is not complited
1104 17:31:30 [Debug] :  AppLifecycleState.inactive
1104 17:31:31 [Debug] :  AppLifecycleState.paused
1104 17:31:35 [Debug] :  AppLifecycleState.inactive
1104 17:31:35 [Debug] :  AppLifecycleState.resumed
1104 17:31:35 [Debug] :  Use lovelace is true
1104 17:31:35 [Warning] :  Previous fetch is not complited
1104 17:31:35 [Debug] :  [Received] => event.state_changed: weather.dark_sky
1104 17:31:36 [Debug] :  AppLifecycleState.inactive
1104 17:31:36 [Debug] :  AppLifecycleState.paused
1104 17:31:48 [Debug] :  [Received] => event.state_changed: sensor.time
1104 17:32:17 [Debug] :  [Received] => event.state_changed: sun.sun
1104 17:32:48 [Debug] :  [Received] => event.state_changed: sensor.time
1104 17:33:17 [Debug] :  [Received] => event.state_changed: sun.sun
1104 17:33:48 [Debug] :  [Received] => event.state_changed: sensor.time
1104 17:34:17 [Debug] :  [Received] => event.state_changed: sun.sun
1104 17:34:47 [Debug] :  [Received] => event.state_changed: weather.dark_sky
1104 17:34:48 [Debug] :  [Received] => event.state_changed: sensor.time
1104 17:35:17 [Debug] :  [Received] => event.state_changed: sun.sun
1104 17:35:28 [Debug] :  AppLifecycleState.inactive
1104 17:35:28 [Debug] :  AppLifecycleState.resumed
1104 17:35:28 [Debug] :  Use lovelace is true
1104 17:35:28 [Warning] :  Previous fetch is not complited
1104 17:35:32 [Debug] :  AppLifecycleState.inactive
1104 17:35:33 [Debug] :  AppLifecycleState.paused
1104 17:35:48 [Debug] :  [Received] => event.state_changed: sensor.time
1104 17:36:17 [Debug] :  [Received] => event.state_changed: sun.sun
1104 17:36:42 [Debug] :  [Received] => event.state_changed: sensor.illumination_34ce008130bf
1104 17:36:48 [Debug] :  [Received] => event.state_changed: sensor.time
1104 17:37:17 [Debug] :  [Received] => event.state_changed: sun.sun
1104 17:37:27 [Debug] :  AppLifecycleState.inactive
1104 17:37:27 [Debug] :  AppLifecycleState.resumed
1104 17:37:27 [Debug] :  Use lovelace is true
1104 17:37:27 [Warning] :  Previous fetch is not complited
```

**Comment by estevez-dev** [comment]
Fixed in 0.3.5
